version: '3.8'

services:
  db_activity:
    container_name: db_activity
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4307:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php_activity:
    container_name: php_activity
    build:
      context: ./php
    ports:
      - '9001:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - db_activity

  nginx_acyivity:
    container_name: nginx_activity
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_activity
      - db_activity
